@layout(MainLayout>view)

@inlet(title)
User Login
@endinlet

@inlet(content)
<section class="vh-100">
  <div class="container-fluid h-100">
    <div class="row h-100">
      <div class="col-md-6 d-flex flex-column justify-content-center align-items-center text-black">

        <div class="px-5 ms-xl-4">
          <i class="fas fa-crow fa-2x me-3 pt-5 mt-xl-4" style="color: #709085;"></i>
          <span class="h1 fw-bold mb-0">Medical Prescription System</span>
        </div>

        <div class="d-flex align-items-center h-custom-2 px-md-5 mt-5 pt-5 pt-xl-0 mt-xl-n5">
          <form class="" style="width: clamp(20rem, 5vw,24rem);">

            <h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Log in</h3>

            <div class="form-outline mb-4">
              <input type="email" id="form2Example18" class="form-control form-control-lg" />
              <label class="form-label" for="form2Example18">Email address</label>
            </div>

            <div class="form-outline mb-4">
              <input type="password" id="form2Example28" class="form-control form-control-lg" />
              <label class="form-label" for="form2Example28">Password</label>
            </div>

            <div class="pt-1 mb-4 d-flex d-md-block">
              <button class="btn btn-success btn-lg btn-block m-auto" type="button">Login</button>
            </div>

            <p class="small mb-5 pb-lg-2 text-center text-md-start"><a class="text-muted" href="#!">Forgot password?</a></p>
            <p class="text-center text-md-start">Don't have an account? <a href="#!" class="link-success">Register here</a></p>

          </form>
        </div>

      </div>
      <div class="col-md-6 px-0 d-none d-md-block">
        <img src="assets/images/login-image.jpg"
          alt="Login image" class="w-100 vh-100 object-fit-cover object-position-center">
      </div>
    </div>
  </div>
</section>
@endinlet